namespace WinFormsApp
{
    public class CompanyLabel
    {
        // Properties
        public string Text { get; set; } = "Default Company";
        public Font Font { get; set; } = new Font("Arial", 24, FontStyle.Bold);
        public SolidBrush Brush { get; set; } = new SolidBrush(Color.Black);

        // Default ctor will be generated by C# compiler


        // Methods
        public void DrawOnCenter(Graphics graphicsObj)
        {
            graphicsObj.DrawString(Text, Font, Brush, (1920 / 2 - 150), 80);
        }
    }    

}
